name: mapa_apresentacao
description: Sistema de gerenciamento de apresentações culturais
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0 #'>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # Estado e gerenciamento
  provider: ^6.1.1

  # Armazenamento local
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0

  # Rede (WebSocket + UDP)
  web_socket_channel: ^3.0.3

  # Áudio
  just_audio: ^0.10.5
  file_picker: ^10.3.7

  # Utilitários
  uuid: ^4.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/audio/